apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileuploader
  namespace: fileuploader
  labels:
    app: fileuploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileuploader
  template:
    metadata:
      labels:
        app: fileuploader
    spec:
      containers:
        - name: fileuploader-service
          image: public.ecr.aws/s5l7s8c1/capestone/files3:rollout
          ports:
            - containerPort: 80
            - containerPort: 3000
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: fileuploader-config
                  key: AWS_REGION
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: fileuploader-config
                  key: S3_BUCKET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
      restartPolicy: Always
