apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileuploader-deployment
  namespace: fileuploader
  labels:
    app: fileuploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileuploader
  template:
    metadata:
      labels:
        app: fileuploader
    spec:
      containers:
        - name: fileuploader-service
          image: public.ecr.aws/s5l7s8c1/capestone/files3:latest
          ports:
            - containerPort: 80
            - containerPort: 3000
      restartPolicy: Always
