version: '3.1'

services:
  client:
    image: client-fileuploader:latest
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped

  server:
    image: server-fileuploader:latest
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - ./.env
