apiVersion: v1
kind: ServiceAccount
metadata:
  name: fileuploader-sa
  namespace: fileuploader
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::652821469770:role/eksctl-eks-capestone-project-2-dev2-eks-addon-Role1-PCq9HY7GDqk8
