apiVersion: v1
kind: Service
metadata:
  name: argocd-image-updater-svc
  namespace: argocd
spec:
  selector:
    app: argocd-image-updater
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
