apiVersion: v1
kind: Service
metadata:
  name: fileuploader-svc
  namespace: fileuploader
spec:
  selector:
    app: fileuploader
  ports:
    - name: frontend
      port: 80
      targetPort: 80
    - name: backend
      port: 3000
      targetPort: 3000
  type: LoadBalancer  # or ClusterIP if backend should stay internal
