apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: fileuploader
spec:
  selector:
    app: fileuploader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: fileuploader
spec:
  selector:
    app: fileuploader
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

