name: ECR Public CI/CD

on:
  push:
    branches: ["docker"]

jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker build -t fileuploader:latest .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: fileuploader:latest
          format: table


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Tag and Push images to ECR Public
        env:
          PUBLIC_REPO_URI: public.ecr.aws/s5l7s8c1/capestone/files3
        run: |
          echo "Pushing image to $PUBLIC_REPO_URI in us-east-1"

          docker tag fileuploader:latest $PUBLIC_REPO_URI:1.5

          docker push $PUBLIC_REPO_URI:1.5

